annonce_index:
    path:     /
    defaults: { _controller: "PetiteAnnonceBundle:annonce:index" }
    methods:  GET

annonce_show:
    path:     /{id}/show
    defaults: { _controller: "PetiteAnnonceBundle:annonce:show" }
    methods:  GET

annonce_new:
    path:     /new
    defaults: { _controller: "PetiteAnnonceBundle:annonce:new" }
    methods:  [GET, POST]

annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "PetiteAnnonceBundle:annonce:edit" }
    methods:  [GET, POST]

annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "PetiteAnnonceBundle:annonce:delete" }
    methods:  DELETE
