categorie_index:
    path:     /
    defaults: { _controller: "PetiteAnnonceBundle:categorie:index" }
    methods:  GET

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "PetiteAnnonceBundle:categorie:show" }
    methods:  GET

categorie_new:
    path:     /new
    defaults: { _controller: "PetiteAnnonceBundle:categorie:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "PetiteAnnonceBundle:categorie:edit" }
    methods:  [GET, POST]

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "PetiteAnnonceBundle:categorie:delete" }
    methods:  DELETE
