AppBundle\Entity\Student:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StudentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '40'
    lifecycleCallbacks: {  }
